# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
  BuildConfiguration: "Release"
jobs:
- job: 
  displayName: Build application
  pool:
   vmImage: 'ubuntu-latest' 
  steps:
    - task: GitVersion@5
      displayName: GitVersion 
      inputs:
        runtime: 'core'
    
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '**/*.MSSqlDatabase.csproj'
        arguments: '-c $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
        versioningScheme: byBuildNumber
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack' 
      inputs: 
        command: pack
        packagesToPack: '$(Parameters.projects)' 
        nobuild: true 
        versioningScheme: byEnvVar 
        versionEnvVar: GitVersion.NuGetVersion
    - task: DotNetCoreCLI@2
      displayName: 'dotnet nuget push'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget.org'
    

