# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
  BuildConfiguration: "Release"
  ProjectsPath :  '**/*.MSSqlDatabase.csproj'
   
jobs:
- job: 
  displayName: Build application
  pool:
   vmImage: 'ubuntu-latest' 
  steps:
    - task: GitVersion@5
      displayName: GitVersion 
      inputs:
        runtime: 'core'
    
    - task: UseDotNet@2
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: $(ProjectsPath)
        arguments: '-c $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
        versioningScheme: byBuildNumber
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack' 
      inputs: 
        command: pack
        packagesToPack: $(ProjectsPath) 
        nobuild: true 
        versioningScheme: byEnvVar 
        versionEnvVar: GitVersion.NuGetVersion
    - task: NuGetCommand@2
      displayName: 'Nuget push'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget.org'
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('true', variables['FORCE_PUSH_NUGET']))
    - task: git-tag-on-release-task@8
      inputs:
        staticTagName: '$(GitVersion.NuGetVersion)'